# web port
server.port=8081
# no web
#spring.main.web-environment=false

# log config
logging.config=classpath:logback.xml


### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
xxl.job.admin.addresses=http://127.0.0.1:18080/xxl-job-admin
### xxl-job access token
xxl.job.admin.accessToken=default_token
### xxl-job timeout by second, default 3s
xxl.job.admin.timeout=3

### xxl-job executor enable, default true
xxl.job.executor.enabled=true
### xxl-job executor appname
xxl.job.executor.appname=xxl-job-executor-sample
### xxl-job boost group title
xxl.job.executor.group-title=\u901A\u7528\u6267\u884C\u5668Sample
### xxl-job boost sync mode: DISABLED / CREATE_ONLY / CREATE_UPDATE
xxl.job.executor.sync-mode=CREATE_UPDATE
### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
xxl.job.executor.address=
### xxl-job executor server-info
xxl.job.executor.ip=
### xxl-job executor transport: NETTY_EMBED / SPRING_HTTP
xxl.job.executor.transport=SPRING_HTTP
### xxl-job executor log-path
xxl.job.executor.logpath=./logs/xxl-job/jobhandler
### xxl-job executor log-retention-days
xxl.job.executor.logretentiondays=30

### xxl-job boost optional Logback capture, default false
#xxl.job.executor.log-capture.enabled=true
#xxl.job.executor.log-capture.level=INFO
#xxl.job.executor.log-capture.max-event-length=4096
#xxl.job.executor.log-capture.max-events-per-job=2000
#xxl.job.executor.log-capture.include-packages=com.xxl.job.executor.
#xxl.job.executor.log-capture.exclude-packages=org.springframework.,spring.,com.zaxxer.hikari.
