FROM eclipse-temurin:17-jre

LABEL maintainer="xuxueli"

ENV PARAMS=""
ENV TZ=PRC

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

ARG PROJECT_VERSION=0.9.4

COPY xxl-job-executor-samples/xxl-job-executor-sample-springboot/target/xxl-job-executor-sample-springboot-${PROJECT_VERSION}.jar /app.jar

ENTRYPOINT ["sh", "-c", "exec java $JAVA_OPTS ${LOG_HOME:+-DLOG_HOME=$LOG_HOME} -jar /app.jar $PARAMS"]
