/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  alerts: () => import("@/views/alerts/index.vue"),
  audits: () => import("@/views/audits/index.vue"),
  executors: () => import("@/views/executors/index.vue"),
  "failure-aggregates": () => import("@/views/failure-aggregates/index.vue"),
  governance: () => import("@/views/governance/index.vue"),
  help: () => import("@/views/help/index.vue"),
  home: () => import("@/views/home/index.vue"),
  "job-code": () => import("@/views/job-code/index.vue"),
  jobs: () => import("@/views/jobs/index.vue"),
  "log-detail": () => import("@/views/log-detail/index.vue"),
  logs: () => import("@/views/logs/index.vue"),
  "slow-tasks": () => import("@/views/slow-tasks/index.vue"),
  users: () => import("@/views/users/index.vue"),
};
