/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'alerts',
    path: '/alerts',
    component: 'layout.base$view.alerts',
    meta: {
      title: 'alerts',
      i18nKey: 'route.alerts',
      icon: 'mdi:bell-alert-outline',
      order: 4.5,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'audits',
    path: '/audits',
    component: 'layout.base$view.audits',
    meta: {
      title: 'audits',
      i18nKey: 'route.audits',
      icon: 'mdi:clipboard-text-search-outline',
      order: 6,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'executors',
    path: '/executors',
    component: 'layout.base$view.executors',
    meta: {
      title: 'executors',
      i18nKey: 'route.executors',
      icon: 'mdi:server-outline',
      order: 2
    }
  },
  {
    name: 'failure-aggregates',
    path: '/failure-aggregates',
    component: 'layout.base$view.failure-aggregates',
    meta: {
      title: 'failure-aggregates',
      i18nKey: 'route.failure-aggregates',
      icon: 'mdi:alert-decagram-outline',
      order: 5
    }
  },
  {
    name: 'governance',
    path: '/governance',
    component: 'layout.base$view.governance',
    meta: {
      title: 'governance',
      i18nKey: 'route.governance',
      icon: 'mdi:view-dashboard-outline',
      order: 1.5,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'help',
    path: '/help',
    component: 'layout.base$view.help',
    meta: {
      title: 'help',
      i18nKey: 'route.help',
      icon: 'mdi:help-circle-outline',
      order: 8
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'job-code',
    path: '/job-code',
    component: 'layout.base$view.job-code',
    props: true,
    meta: {
      title: 'job-code',
      i18nKey: 'route.job-code',
      hideInMenu: true,
      activeMenu: 'jobs'
    }
  },
  {
    name: 'jobs',
    path: '/jobs',
    component: 'layout.base$view.jobs',
    meta: {
      title: 'jobs',
      i18nKey: 'route.jobs',
      icon: 'mdi:briefcase-outline',
      order: 3
    }
  },
  {
    name: 'log-detail',
    path: '/log-detail',
    component: 'layout.base$view.log-detail',
    props: true,
    meta: {
      title: 'log-detail',
      i18nKey: 'route.log-detail',
      hideInMenu: true,
      activeMenu: 'logs'
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'logs',
    path: '/logs',
    component: 'layout.base$view.logs',
    meta: {
      title: 'logs',
      i18nKey: 'route.logs',
      icon: 'mdi:file-document-outline',
      order: 4
    }
  },
  {
    name: 'slow-tasks',
    path: '/slow-tasks',
    component: 'layout.base$view.slow-tasks',
    meta: {
      title: 'slow-tasks',
      i18nKey: 'route.slow-tasks',
      icon: 'mdi:speedometer-slow',
      order: 8
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:account-group-outline',
      order: 9
    }
  }
];
